##端口号
server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
#    数据库模式指定，0~15一共16个模式，默认选择0
    database: 1
#    spring boot2中默认使用lettuce作为redis客户端
    lettuce:
      pool:
#        连接池最大连接池
        max-active: 8
#        连接池最大阻塞时间，单位毫秒，负数表示没有限制
        max-wait: -1
#        连接池中最大空闲连接数量
        max-idle: 8
#        连接池中最小空闲连接数量
        min-idle: 0