server:
  port: 8080

spring:
#  session:
#    store-type: redis
  resources:
    static-locations: classpath:/static/
  redis:
    host: localhost
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
