server:
  port: 8080

spring:
#  数据源信息
#  datasource:
#    url: jdbc:mysql://10.225.12.98:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host:  10.225.12.96
    port: 6379
    password: bgiredis
    #    数据库模式指定，0~15一共16个模式，默认选择0
    database: 10
    #    spring boot2中默认使用lettuce作为redis客户端
    lettuce:
      pool:
        #        连接池最大连接池
        max-active: 8
        #        连接池最大阻塞时间，单位毫秒，负数表示没有限制
        max-wait: -1
        #        连接池中最大空闲连接数量
        max-idle: 8
        #        连接池中最小空闲连接数量
        min-idle: 0
